http:
  port: 8088
  mode: debug
  read-time-out: 60 #单位为s、请求的超时时间设置
  write-time-out: 60

log:
  level: info
  filename: app.log
  maxSize: 10
  maxAge: 30
  maxBackups: 30

datasource:
  addr: 127.0.0.1:3306
  dsn: root:root@tcp(127.0.0.1:3306)/permission?charset=utf8mb4&parseTime=True
  read-dsn: root:root@tcp(127.0.0.1:3306)/permission?charset=utf8mb4&parseTime=True
    - root:root@tcp(127.0.0.1:3306)/permission?charset=utf8mb4&parseTime=True
    - root:root@tcp(127.0.0.1:3306)/permission?charset=utf8mb4&parseTime=True
  active: 200
  idle: 200
  idle-timeout: 60 #单位都是s
  query-timeout: 60
  exec-timeout: 60
  tran-timeout: 60