# env=test
bigbro.diaodu_url: http://10.26.21.86:16700/scheduler
#bigbro.diaodu_url: http://scheduler.diaodu.data.lianjia.com/scheduler
#alarm.mail.url: http://test-sms.data.lianjia.com/soa/smstask/addSmsTask
alarm.mail.url: http://sms.data.lianjia.com/soa/smstask/addSmsTask

insert:
  batch: 1000

auth:
  server:
    url: http://test-auth.api.ke.com

once:
  server:
    url: http://10.10.16.53:8096

datasource:
  pool:
    monitor:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://kgw.ke.com:10988/scheduler_index_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      jdbc-url: jdbc:mysql://m11159.mars.test.mysql.ljnode.com:11159/scheduler_index_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: cQYXUgsdl7
    scheduler:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://kgw.ke.com:10988/scheduler_debug?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      jdbc-url: jdbc:mysql://kgw.ke.com:10988/scheduler_debug?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: cQYXUgsdl7
    manager:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://kgw.ke.com:10988/executor_debug?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      jdbc-url: jdbc:mysql://m11159.mars.test.mysql.ljnode.com:11159/executor_debug?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: cQYXUgsdl7
    databus:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://kgw.ke.com:10988/executor_debug?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      jdbc-url: jdbc:mysql://m11159.mars.test.mysql.ljnode.com:11159/executor_debug?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: cQYXUgsdl7
spring:
  discovery:
    client:
      server-name: test.eureka.ke.com
      server-port: 10140
  config:
    apollo:
      server: http://test.config.apollo.ke.com
      environment: TEST
      # 开启placeholder在运行时自动更新功能，如不需要可关闭
      auto-update-injected: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  dubbo:
    registry-cache: ${java.io.tmpdir:-/tmp}
    application:
      name: ${spring.application.name}
    protocol:
      name: dubbo
      port: 8880
    provider:
      timeout: 3000
      retries: 1
    consumer:
      timeout: 3000
      retries: 3
    config-center:
      address: zk01-test.lianjia.com:2181
      namespace: /configcenter
      username: configcenter
      password: Bb79177b89
    registries:
      bigdata:
        protocol: zookeeper
        address: zk01-test.lianjia.com:2181,zk02-test.lianjia.com:2181,zk03-test.lianjia.com:2181
        group: bigdata/max
        username: bigdata
        password: q4wnljGI9G
        file: /tmp/${spring.application.name}-jichu.cache
        register: false
#eureka:
#  client:
#    use-dns-for-fetching-service-urls: true
#    eureka-server-d-n-s-name: test.eureka.ke.com
#    eureka-server-port: 10140
#    eureka-server-u-r-l-context: /eureka
#    region: cn-bj-1
#    availability-zones.cn-bj-1: ${IDC:mars}
#    module-name: bigdata-diaodu-statserver

hawk:
  app-name: bigdata-diaodu-statserver
  server:
    host: 10.26.33.56
    socket-port: 14604

logging:
  level:
    root: INFO
    org:
      springframework: INFO

lianjia-schedule:
  env: official_offline_3
  project: test-stat.diaodu.data.ke.com
  token: jk2zz2my1cpikiikwut5
  enable: true
